library(MasterBayes)
data(WarblerP)
data(WarblerG)
res1<-expression(varPed("terr",gender="Female", relational="OFFSPRING",restrict="=="))
res2<-expression(varPed(x="offspring",gender=NULL, relational=FALSE,restrict=0))
var1<-expression(varPed(x=c("lat", "long"),gender="Male",  relational="OFFSPRING"))
PdP<-PdataPed(formula=list(res1, res2, var1), data=WarblerP, USsire=TRUE)
GdP<-GdataPed(G=WarblerG, categories=NULL)                 
sP<-startPed(estG=FALSE, E1=0.005, E2=0.005, A=extractA(WarblerG), estUSsire=FALSE, USsire = 10)
PdPCervus<-PdataPed(formula=list(res1, res2), data=WarblerP, USsire=TRUE)
model1<-MCMCped(PdP=PdPCervus, GdP=GdP, sP=sP, verbose=T)
ped1<-modeP(model1$P, threshold=0)
